### ISSUE TITLE
Failed to install plugin

### ISSUE THREAD

**Issue by deuts** [yy4382/obsidian-static-site-export#5]
I just tried installing it now (v. 2.0.3), but I'm always getting "Failed to install plugin" error.

**Comment by yy4382** [comment]
Really sorry that I forgot to set the 2.0.3 version from draft to a actual release 💀
Try now!

If you have any problem using it (or feature request), please let me know, I'm happy to help!

**Comment by deuts** [comment]
It's working now. Thanks.
