### ISSUE TITLE
Published property in frontmatter

### ISSUE THREAD

**Issue by deuts** [yy4382/obsidian-static-site-export#6]
Unfortunately, the `published` frontmatter in Hugo is an alias to the `publishDate` (see [here](https://gohugo.io/content-management/front-matter/#published)). That way, it'll expect a date for that property during build. Is there any way around this? Maybe remove the published in the frontmatter when it uploads to github, or change the property for which to search when uploading to Github?

**Comment by yy4382** [comment]
The "published" key is now configurable in v2.1.0

**Comment by deuts** [comment]
Thanks! This is very helpful!
